/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.unindra.inventory.view;

import com.unindra.inventory.db.Barang;
import com.unindra.inventory.db.BarangKeluar;
import com.unindra.inventory.db.BarangMasuk;
import com.unindra.inventory.db.Gudang;
import com.unindra.inventory.db.Kategori;
import com.unindra.inventory.db.Pemasok;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author herwi
 */
public class DataTransaksiPanel extends javax.swing.JPanel {
    
    private static List<String> pemasokList = new ArrayList<>();
    private static List<String> kdBarangList = new ArrayList<>();
    private static List<String> nmBarangList = new ArrayList<>();
    private static Barang barang;
    private static BarangMasuk barangMasuk;
    private static BarangKeluar barangKeluar;
    private static Kategori kategori;
    private static Gudang gudang;
    private static Pemasok pemasok;

    /**
     * Creates new form DataMasterPanel
     */
    public DataTransaksiPanel() {
        initComponents();
        
        barang   = new Barang();
        kategori = new Kategori();
        gudang   = new Gudang();
        pemasok  = new Pemasok();
        
        barangMasuk = new BarangMasuk();
        barangKeluar = new BarangKeluar();
        
        loadBarangMasuk();
        loadDetailBarangMasuk( null );
        loadPemasok();
        loadBarang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        detailBarangMasukTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        barangMasukTable = new javax.swing.JTable();
        simpanPemasok1 = new javax.swing.JButton();
        editPemasok4 = new javax.swing.JButton();
        hapusPemasok4 = new javax.swing.JButton();
        hapusPemasok5 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        kodeBM = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        keteranganBM = new javax.swing.JTextField();
        simpanPemasok2 = new javax.swing.JButton();
        editPemasok5 = new javax.swing.JButton();
        hapusPemasok6 = new javax.swing.JButton();
        hapusPemasok7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        kodeDBM = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        barangDBM = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jumlahDBM = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        keteranganDBM = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        detailBarangKeluarTable = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        barangKeluarTable = new javax.swing.JTable();
        simpanPemasok3 = new javax.swing.JButton();
        editPemasok6 = new javax.swing.JButton();
        hapusPemasok8 = new javax.swing.JButton();
        hapusPemasok9 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        kodeBK = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        keteranganBK = new javax.swing.JTextField();
        simpanPemasok4 = new javax.swing.JButton();
        editPemasok7 = new javax.swing.JButton();
        hapusPemasok10 = new javax.swing.JButton();
        hapusPemasok11 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        kodeDBK = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        barangDBK = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jumlahDBK = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        keteranganDBK = new javax.swing.JTextField();

        setBackground(new java.awt.Color(60, 91, 111));

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyPressed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(60, 91, 111));

        detailBarangMasukTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        detailBarangMasukTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                detailBarangMasukTableMousePressed(evt);
            }
        });
        jScrollPane5.setViewportView(detailBarangMasukTable);

        barangMasukTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        barangMasukTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barangMasukTableMousePressed(evt);
            }
        });
        jScrollPane6.setViewportView(barangMasukTable);

        simpanPemasok1.setText("Simpan");
        simpanPemasok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPemasok1ActionPerformed(evt);
            }
        });

        editPemasok4.setText("Edit");
        editPemasok4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPemasok4ActionPerformed(evt);
            }
        });

        hapusPemasok4.setText("Hapus");
        hapusPemasok4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasok4ActionPerformed(evt);
            }
        });

        hapusPemasok5.setText("Batal");
        hapusPemasok5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasok5ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(242, 242, 242));
        jLabel19.setText("KODE");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(242, 242, 242));
        jLabel20.setText("SUPPLIER");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(242, 242, 242));
        jLabel21.setText("KETERANGAN");

        simpanPemasok2.setText("Simpan");
        simpanPemasok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPemasok2ActionPerformed(evt);
            }
        });

        editPemasok5.setText("Edit");
        editPemasok5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPemasok5ActionPerformed(evt);
            }
        });

        hapusPemasok6.setText("Hapus");
        hapusPemasok6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasok6ActionPerformed(evt);
            }
        });

        hapusPemasok7.setText("Batal");
        hapusPemasok7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasok7ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(60, 91, 111));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(242, 242, 242));
        jLabel25.setText("KODE DETAIL");

        kodeDBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeDBMActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(242, 242, 242));
        jLabel24.setText("BARANG");

        barangDBM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(242, 242, 242));
        jLabel23.setText("JUMLAH");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(242, 242, 242));
        jLabel22.setText("KETERANGAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(keteranganDBM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jumlahDBM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodeDBM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barangDBM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodeDBM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barangDBM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlahDBM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keteranganDBM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(simpanPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(editPemasok4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(hapusPemasok4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(hapusPemasok5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(simpanPemasok2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(editPemasok5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(hapusPemasok6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(hapusPemasok7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(keteranganBM, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kodeBM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kodeBM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keteranganBM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(editPemasok4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hapusPemasok4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hapusPemasok5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(simpanPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(editPemasok5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hapusPemasok6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hapusPemasok7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(simpanPemasok2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Barang Masuk", jPanel6);

        jPanel2.setBackground(new java.awt.Color(60, 91, 111));

        detailBarangKeluarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        detailBarangKeluarTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                detailBarangKeluarTableMousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(detailBarangKeluarTable);

        barangKeluarTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        barangKeluarTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barangKeluarTableMousePressed(evt);
            }
        });
        jScrollPane8.setViewportView(barangKeluarTable);

        simpanPemasok3.setText("Simpan");
        simpanPemasok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPemasok3ActionPerformed(evt);
            }
        });

        editPemasok6.setText("Edit");
        editPemasok6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPemasok6ActionPerformed(evt);
            }
        });

        hapusPemasok8.setText("Hapus");
        hapusPemasok8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasok8ActionPerformed(evt);
            }
        });

        hapusPemasok9.setText("Batal");
        hapusPemasok9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasok9ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(242, 242, 242));
        jLabel26.setText("KODE");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(242, 242, 242));
        jLabel27.setText("GUDANG");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(242, 242, 242));
        jLabel28.setText("KETERANGAN");

        simpanPemasok4.setText("Simpan");
        simpanPemasok4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPemasok4ActionPerformed(evt);
            }
        });

        editPemasok7.setText("Edit");
        editPemasok7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPemasok7ActionPerformed(evt);
            }
        });

        hapusPemasok10.setText("Hapus");
        hapusPemasok10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasok10ActionPerformed(evt);
            }
        });

        hapusPemasok11.setText("Batal");
        hapusPemasok11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasok11ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(60, 91, 111));
        jPanel3.setToolTipText("");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(242, 242, 242));
        jLabel29.setText("KODE DETAIL");

        kodeDBK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodeDBKActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(242, 242, 242));
        jLabel30.setText("BARANG");

        barangDBK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(242, 242, 242));
        jLabel31.setText("JUMLAH");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(242, 242, 242));
        jLabel32.setText("KETERANGAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(keteranganDBK, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jumlahDBK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodeDBK, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barangDBK, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kodeDBK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(barangDBK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlahDBK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keteranganDBK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(simpanPemasok3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(editPemasok6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(hapusPemasok8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(hapusPemasok9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(simpanPemasok4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(editPemasok7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(hapusPemasok10, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(hapusPemasok11, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(keteranganBK, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kodeBK, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kodeBK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keteranganBK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(editPemasok6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hapusPemasok8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hapusPemasok9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(simpanPemasok3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(editPemasok7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hapusPemasok10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hapusPemasok11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(simpanPemasok4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Barang Keluar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyPressed

    }//GEN-LAST:event_jTabbedPane1KeyPressed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        switch (jTabbedPane1.getSelectedIndex()) {
            case 0:
                loadBarangMasuk();
                loadDetailBarangMasuk( null );
                loadPemasok();
                loadBarang();
                break;
            case 1:
                loadBarangKeluar();
                loadDetailBarangKeluar( null );
                loadPemasok();
                loadBarang();
                break;
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void hapusPemasok5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasok5ActionPerformed
        clearBMForm();
        kodeBM.setEnabled( true );
        loadDetailBarangMasuk( null );
    }//GEN-LAST:event_hapusPemasok5ActionPerformed

    private void hapusPemasok4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasok4ActionPerformed
        barangMasuk.delete(kodeBM.getText());
        clearBMForm();
        loadBarangMasuk();
    }//GEN-LAST:event_hapusPemasok4ActionPerformed

    private void editPemasok4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPemasok4ActionPerformed
        barangMasuk.update(kodeBM.getText(), pemasokList.get(jComboBox2.getSelectedIndex()), keteranganBM.getText());
        clearBMForm();
        loadBarangMasuk();
    }//GEN-LAST:event_editPemasok4ActionPerformed

    private void simpanPemasok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPemasok1ActionPerformed
        barangMasuk.create(kodeBM.getText(), pemasokList.get(jComboBox2.getSelectedIndex()), keteranganBM.getText());
        clearBMForm();
        loadBarangMasuk();
    }//GEN-LAST:event_simpanPemasok1ActionPerformed

    private void barangMasukTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangMasukTableMousePressed
        String kode_part = (String) barangMasukTable.getValueAt(barangMasukTable.getSelectedRow(), 1);               
        String pemasok_part = (String) barangMasukTable.getValueAt(barangMasukTable.getSelectedRow(), 2);                    
        String keterangan_part = (String) barangMasukTable.getValueAt(barangMasukTable.getSelectedRow(), 4);
        kodeBM.setText( kode_part );
        keteranganBM.setText(keterangan_part);
        for (int i=0; i<jComboBox2.getItemCount(); i++) {
            if (jComboBox2.getModel().getElementAt(i).contains(pemasok_part)) {
                jComboBox2.setSelectedIndex(i);
            }
        }
        kodeBM.setEnabled( false );
        loadDetailBarangMasuk( kode_part );
    }//GEN-LAST:event_barangMasukTableMousePressed

    private void simpanPemasok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPemasok2ActionPerformed
        String pemasok_part = pemasokList.get(jComboBox2.getSelectedIndex());
        String kode_barang_part = kdBarangList.get(barangDBM.getSelectedIndex());
        String nama_barang_part = nmBarangList.get(barangDBM.getSelectedIndex());
        barangMasuk.createDetail(kodeDBM.getText(), kodeBM.getText(), pemasok_part, kode_barang_part, nama_barang_part,(int) jumlahDBM.getValue(), keteranganDBM.getText());
        loadDetailBarangMasuk(kodeBM.getText());
    }//GEN-LAST:event_simpanPemasok2ActionPerformed

    private void editPemasok5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPemasok5ActionPerformed
        String kode_barang_part = kdBarangList.get(barangDBM.getSelectedIndex());
        String nama_barang_part = nmBarangList.get(barangDBM.getSelectedIndex());
        barangMasuk.updateDetail(kodeDBM.getText(), kode_barang_part, nama_barang_part, (int) jumlahDBM.getValue(), keteranganDBM.getText());
        loadDetailBarangMasuk(kodeBM.getText().isBlank() ? null : kodeBM.getText() );
    }//GEN-LAST:event_editPemasok5ActionPerformed

    private void hapusPemasok6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasok6ActionPerformed
        barangMasuk.deleteDetail(kodeDBM.getText());
        loadDetailBarangMasuk(kodeBM.getText().isBlank() ? null : kodeBM.getText() );
    }//GEN-LAST:event_hapusPemasok6ActionPerformed

    private void hapusPemasok7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasok7ActionPerformed
        clearDBMForm();
        kodeDBM.setEnabled( true );
    }//GEN-LAST:event_hapusPemasok7ActionPerformed

    private void kodeDBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeDBMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeDBMActionPerformed

    private void detailBarangMasukTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailBarangMasukTableMousePressed
        String kode_part = (String) detailBarangMasukTable.getValueAt(detailBarangMasukTable.getSelectedRow(), 1);                    
        int jumlah_part = (int) detailBarangMasukTable.getValueAt(detailBarangMasukTable.getSelectedRow(), 5);                 
        String keterangan_part = (String) detailBarangMasukTable.getValueAt(detailBarangMasukTable.getSelectedRow(), 7);             
        String nm_barang_part = (String) detailBarangMasukTable.getValueAt(detailBarangMasukTable.getSelectedRow(), 4); 
        kodeDBM.setText( kode_part );
        keteranganDBM.setText(keterangan_part);
        jumlahDBM.setValue(jumlah_part);
        for (int i=0; i<barangDBM.getItemCount(); i++) {
            if (barangDBM.getModel().getElementAt(i).contains(nm_barang_part)) {
                barangDBM.setSelectedIndex(i);
            }
        }
        kodeDBM.setEnabled( false );
    }//GEN-LAST:event_detailBarangMasukTableMousePressed

    private void detailBarangKeluarTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detailBarangKeluarTableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailBarangKeluarTableMousePressed

    private void barangKeluarTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangKeluarTableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_barangKeluarTableMousePressed

    private void simpanPemasok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPemasok3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanPemasok3ActionPerformed

    private void editPemasok6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPemasok6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPemasok6ActionPerformed

    private void hapusPemasok8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasok8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusPemasok8ActionPerformed

    private void hapusPemasok9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasok9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusPemasok9ActionPerformed

    private void simpanPemasok4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPemasok4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_simpanPemasok4ActionPerformed

    private void editPemasok7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPemasok7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editPemasok7ActionPerformed

    private void hapusPemasok10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasok10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusPemasok10ActionPerformed

    private void hapusPemasok11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasok11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hapusPemasok11ActionPerformed

    private void kodeDBKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodeDBKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodeDBKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> barangDBK;
    private javax.swing.JComboBox<String> barangDBM;
    private javax.swing.JTable barangKeluarTable;
    private javax.swing.JTable barangMasukTable;
    private javax.swing.JTable detailBarangKeluarTable;
    private javax.swing.JTable detailBarangMasukTable;
    private javax.swing.JButton editPemasok4;
    private javax.swing.JButton editPemasok5;
    private javax.swing.JButton editPemasok6;
    private javax.swing.JButton editPemasok7;
    private javax.swing.JButton hapusPemasok10;
    private javax.swing.JButton hapusPemasok11;
    private javax.swing.JButton hapusPemasok4;
    private javax.swing.JButton hapusPemasok5;
    private javax.swing.JButton hapusPemasok6;
    private javax.swing.JButton hapusPemasok7;
    private javax.swing.JButton hapusPemasok8;
    private javax.swing.JButton hapusPemasok9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner jumlahDBK;
    private javax.swing.JSpinner jumlahDBM;
    private javax.swing.JTextField keteranganBK;
    private javax.swing.JTextField keteranganBM;
    private javax.swing.JTextField keteranganDBK;
    private javax.swing.JTextField keteranganDBM;
    private javax.swing.JTextField kodeBK;
    private javax.swing.JTextField kodeBM;
    private javax.swing.JTextField kodeDBK;
    private javax.swing.JTextField kodeDBM;
    private javax.swing.JButton simpanPemasok1;
    private javax.swing.JButton simpanPemasok2;
    private javax.swing.JButton simpanPemasok3;
    private javax.swing.JButton simpanPemasok4;
    // End of variables declaration//GEN-END:variables

    /*
    ** Barang Masuk
    */
    private void clearBMForm() {
        kodeBM.setText("");
        keteranganBM.setText("");
    }
    
    private void clearDBMForm() {
        kodeDBM.setText("");
        jumlahDBM.setValue(1);
        keteranganDBM.setText("");
    }
    
    private void loadBarangMasuk() {
        Object[] header = {"#", "Kode", "Supplier", "Tanggal", "Keterangan"};
        DefaultTableModel model = new DefaultTableModel(null, header);
        barangMasukTable.setModel(model);
        
        ResultSet data = barangMasuk.fetchAll();
        int i = 0;
        try {
            while (data.next()){
                String kode_part = data.getString("id_bm");
                String pemasok_part = data.getString("supplier");
                String tanggal_part = data.getString("tanggal");
                String keterangan_part = data.getString("keterangan");
                Object[] datum = {++i, kode_part, pemasok_part, tanggal_part, keterangan_part};
                model.addRow(datum);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadDetailBarangMasuk(String kodeBm) {
        Object[] header = {"#", "Kode", "Kode BM", "Supplier", "Nama Barang", "Jumlah", "Tanggal", "Keterangan"};
        DefaultTableModel model = new DefaultTableModel(null, header);
        detailBarangMasukTable.setModel(model);
        
        ResultSet data;
        if (kodeBm == null) {
            data = barangMasuk.fetchDetailAll();
        } else {
            data = barangMasuk.fetchDetailByIdBm(kodeBm);
        }
        int i = 0;
        try {
            while (data.next()){
                String kode_part = data.getString("id_detail_bm");
                String kode_bm_part = data.getString("id_bm");
                String pemasok_part = data.getString("supplier");
                String nama_barang_part = data.getString("nama_part");
                int jumlah_part = data.getInt("jumlah");
                String tanggal_part = data.getString("tanggal");
                String keterangan_part = data.getString("keterangan");
                Object[] datum = {++i, kode_part, kode_bm_part, pemasok_part, nama_barang_part, jumlah_part, tanggal_part, keterangan_part};
                model.addRow(datum);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadPemasok() {
        String[] body = { };
        DefaultComboBoxModel model = new DefaultComboBoxModel<>( body );
        jComboBox2.setModel( model );
        
        ResultSet data = pemasok.fetchAll();
        try {
            pemasokList.clear();
            while (data.next()){
                String kode_part = data.getString("kode_supplier");
                String nama_part = data.getString("nama_supplier");
                String formatted = "["+ kode_part +"] "+ nama_part;
                pemasokList.add(nama_part);
                model.addElement( formatted );
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadBarang() {
        String[] body = { };
        DefaultComboBoxModel model = new DefaultComboBoxModel<>( body );
        barangDBM.setModel( model );
        
        ResultSet data = barang.fetchAll();
        try {
            kdBarangList.clear();
            nmBarangList.clear();
            while (data.next()){
                String kode_part = data.getString("kode_part");
                String nama_part = data.getString("nama_part");
                String formatted = "["+ kode_part +"] "+ nama_part;
                kdBarangList.add(kode_part);
                nmBarangList.add(nama_part);
                model.addElement( formatted );
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /*
    ** Barang Keluar
    */
    private void clearBKForm() {
        kodeBK.setText("");
        keteranganBK.setText("");
    }
    
    private void clearDBKForm() {
        kodeDBK.setText("");
        jumlahDBK.setValue(1);
        keteranganDBK.setText("");
    }
    
    private void loadBarangKeluar() {
        Object[] header = {"#", "Kode", "Supplier", "Tanggal", "Keterangan"};
        DefaultTableModel model = new DefaultTableModel(null, header);
        barangKeluarTable.setModel(model);
        
        ResultSet data = barangKeluar.fetchAll();
        int i = 0;
        try {
            while (data.next()){
                String kode_part = data.getString("id_bk");
                String pemasok_part = data.getString("gudang");
                String tanggal_part = data.getString("tanggal");
                String keterangan_part = data.getString("keterangan");
                Object[] datum = {++i, kode_part, pemasok_part, tanggal_part, keterangan_part};
                model.addRow(datum);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadDetailBarangKeluar(String kodeBk) {
        Object[] header = {"#", "Kode", "Kode BM", "Supplier", "Nama Barang", "Jumlah", "Tanggal", "Keterangan"};
        DefaultTableModel model = new DefaultTableModel(null, header);
        detailBarangKeluarTable.setModel(model);
        
        ResultSet data;
        if (kodeBk == null) {
            data = barangKeluar.fetchDetailAll();
        } else {
            data = barangKeluar.fetchDetailByIdBk(kodeBk);
        }
        int i = 0;
        try {
            while (data.next()){
                String kode_part = data.getString("id_detail_bk");
                String kode_bm_part = data.getString("id_bk");
                String pemasok_part = data.getString("gudang");
                String nama_barang_part = data.getString("nama_part");
                int jumlah_part = data.getInt("jumlah");
                String tanggal_part = data.getString("tanggal");
                String keterangan_part = data.getString("keterangan");
                Object[] datum = {++i, kode_part, kode_bm_part, pemasok_part, nama_barang_part, jumlah_part, tanggal_part, keterangan_part};
                model.addRow(datum);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
//    private void loadPemasok() {
//        String[] body = { };
//        DefaultComboBoxModel model = new DefaultComboBoxModel<>( body );
//        jComboBox2.setModel( model );
//        
//        ResultSet data = pemasok.fetchAll();
//        try {
//            pemasokList.clear();
//            while (data.next()){
//                String kode_part = data.getString("kode_supplier");
//                String nama_part = data.getString("nama_supplier");
//                String formatted = "["+ kode_part +"] "+ nama_part;
//                pemasokList.add(nama_part);
//                model.addElement( formatted );
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
    
//    private void loadBarang() {
//        String[] body = { };
//        DefaultComboBoxModel model = new DefaultComboBoxModel<>( body );
//        barangDBM.setModel( model );
//        
//        ResultSet data = barang.fetchAll();
//        try {
//            kdBarangList.clear();
//            nmBarangList.clear();
//            while (data.next()){
//                String kode_part = data.getString("kode_part");
//                String nama_part = data.getString("nama_part");
//                String formatted = "["+ kode_part +"] "+ nama_part;
//                kdBarangList.add(kode_part);
//                nmBarangList.add(nama_part);
//                model.addElement( formatted );
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }
}
