/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.unindra.inventory.view;

import com.unindra.inventory.db.Barang;
import com.unindra.inventory.db.Gudang;
import com.unindra.inventory.db.Kategori;
import com.unindra.inventory.db.Pemasok;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author herwi
 */
public class DataMasterPanel extends javax.swing.JPanel {
    
    private static List<String> kategoriList = new ArrayList<>();
    private static Barang barang;
    private static Kategori kategori;
    private static Gudang gudang;
    private static Pemasok pemasok;

    /**
     * Creates new form DataMasterPanel
     */
    public DataMasterPanel() {
        initComponents();
        
        barang   = new Barang();
        kategori = new Kategori();
        gudang   = new Gudang();
        pemasok  = new Pemasok();
        
        loadBarang();
        loadKategoriInBarang();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        barangTable = new javax.swing.JTable();
        simpanPemasok4 = new javax.swing.JButton();
        editPemasok3 = new javax.swing.JButton();
        hapusPemasok3 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        kodeBarang = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        namaBarang = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        keteranganBarang = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        kategoriTable = new javax.swing.JTable();
        simpanPemasok3 = new javax.swing.JButton();
        editPemasok2 = new javax.swing.JButton();
        hapusPemasok2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        kodeKategori = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        namaKategori = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        keteranganKategori = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        gudangTable = new javax.swing.JTable();
        simpanPemasok2 = new javax.swing.JButton();
        editPemasok1 = new javax.swing.JButton();
        hapusPemasok1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        kodeGudang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        namaGudang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        alamatGudang = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        keteranganGudang = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pemasokTable = new javax.swing.JTable();
        simpanPemasok = new javax.swing.JButton();
        editPemasok = new javax.swing.JButton();
        hapusPemasok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        kodePemasok = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        namaPemasok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        phonePemasok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        keteranganPemasok = new javax.swing.JTextField();

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });
        jTabbedPane1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTabbedPane1KeyPressed(evt);
            }
        });

        barangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        barangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barangTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(barangTable);

        simpanPemasok4.setText("Simpan");
        simpanPemasok4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPemasok4ActionPerformed(evt);
            }
        });

        editPemasok3.setText("Edit");
        editPemasok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPemasok3ActionPerformed(evt);
            }
        });

        hapusPemasok3.setText("Hapus");
        hapusPemasok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasok3ActionPerformed(evt);
            }
        });

        jLabel12.setText("jLabel1");

        jLabel13.setText("jLabel1");

        jLabel14.setText("jLabel1");

        jLabel15.setText("jLabel1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanPemasok4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(editPemasok3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(hapusPemasok3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(keteranganBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(keteranganBarang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPemasok4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPemasok3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusPemasok3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Barang", jPanel1);

        kategoriTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        kategoriTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kategoriTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(kategoriTable);

        simpanPemasok3.setText("Simpan");
        simpanPemasok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPemasok3ActionPerformed(evt);
            }
        });

        editPemasok2.setText("Edit");
        editPemasok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPemasok2ActionPerformed(evt);
            }
        });

        hapusPemasok2.setText("Hapus");
        hapusPemasok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasok2ActionPerformed(evt);
            }
        });

        jLabel8.setText("jLabel1");

        jLabel9.setText("jLabel1");

        jLabel10.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanPemasok3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(editPemasok2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(hapusPemasok2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kodeKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(keteranganKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(namaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kodeKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keteranganKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPemasok3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPemasok2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusPemasok2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kategori", jPanel2);

        gudangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gudangTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gudangTableMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(gudangTable);

        simpanPemasok2.setText("Simpan");
        simpanPemasok2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPemasok2ActionPerformed(evt);
            }
        });

        editPemasok1.setText("Edit");
        editPemasok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPemasok1ActionPerformed(evt);
            }
        });

        hapusPemasok1.setText("Hapus");
        hapusPemasok1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasok1ActionPerformed(evt);
            }
        });

        jLabel5.setText("jLabel1");

        jLabel6.setText("jLabel1");

        jLabel7.setText("jLabel1");

        jLabel11.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(keteranganGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanPemasok2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(editPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(hapusPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kodeGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(alamatGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(namaGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kodeGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alamatGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(keteranganGudang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPemasok2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusPemasok1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gudang", jPanel3);

        pemasokTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pemasokTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pemasokTableMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(pemasokTable);

        simpanPemasok.setText("Simpan");
        simpanPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPemasokActionPerformed(evt);
            }
        });

        editPemasok.setText("Edit");
        editPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPemasokActionPerformed(evt);
            }
        });

        hapusPemasok.setText("Hapus");
        hapusPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPemasokActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel1");

        jLabel3.setText("jLabel1");

        jLabel4.setText("jLabel1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(keteranganPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(simpanPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(editPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(hapusPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kodePemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(phonePemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(namaPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kodePemasok, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(phonePemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(keteranganPemasok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hapusPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Supplier", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTabbedPane1KeyPressed
        
    }//GEN-LAST:event_jTabbedPane1KeyPressed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        switch (jTabbedPane1.getSelectedIndex()) {
            case 0:
                loadBarang();
                loadKategoriInBarang();
                break;
            case 1:
                loadKategori();
                break;
            case 2:
                loadGudang();
                break;
            case 3:
                loadPemasok();
                break;
        }
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void simpanPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPemasokActionPerformed
        pemasok.create(kodePemasok.getText(), namaPemasok.getText(), phonePemasok.getText(), keteranganPemasok.getText());
        loadPemasok();
    }//GEN-LAST:event_simpanPemasokActionPerformed

    private void editPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPemasokActionPerformed
        pemasok.update(kodePemasok.getText(), namaPemasok.getText(), phonePemasok.getText(), keteranganPemasok.getText());
        loadPemasok();
    }//GEN-LAST:event_editPemasokActionPerformed

    private void hapusPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasokActionPerformed
        pemasok.delete(kodePemasok.getText());
        loadPemasok();
    }//GEN-LAST:event_hapusPemasokActionPerformed

    private void simpanPemasok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPemasok2ActionPerformed
        gudang.create(kodeGudang.getText(), namaGudang.getText(), alamatGudang.getText(), keteranganGudang.getText());
        loadGudang();
    }//GEN-LAST:event_simpanPemasok2ActionPerformed

    private void editPemasok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPemasok1ActionPerformed
        gudang.update(kodeGudang.getText(), namaGudang.getText(), alamatGudang.getText(), keteranganGudang.getText());
        loadGudang();
    }//GEN-LAST:event_editPemasok1ActionPerformed

    private void hapusPemasok1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasok1ActionPerformed
        gudang.delete(kodeGudang.getText());
        loadGudang();
    }//GEN-LAST:event_hapusPemasok1ActionPerformed

    private void simpanPemasok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPemasok3ActionPerformed
        kategori.create(kodeKategori.getText(), namaKategori.getText(), keteranganKategori.getText());
        loadKategori();
    }//GEN-LAST:event_simpanPemasok3ActionPerformed

    private void editPemasok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPemasok2ActionPerformed
        kategori.update(kodeKategori.getText(), namaKategori.getText(), keteranganKategori.getText());
        loadKategori();
    }//GEN-LAST:event_editPemasok2ActionPerformed

    private void hapusPemasok2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasok2ActionPerformed
        kategori.delete(kodeKategori.getText());
        loadKategori();
    }//GEN-LAST:event_hapusPemasok2ActionPerformed

    private void simpanPemasok4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPemasok4ActionPerformed
        barang.create(kodeBarang.getText(), namaBarang.getText(), kategoriList.get(jComboBox1.getSelectedIndex()), keteranganBarang.getText());
        loadBarang();
    }//GEN-LAST:event_simpanPemasok4ActionPerformed

    private void editPemasok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPemasok3ActionPerformed
        barang.update(kodeBarang.getText(), namaBarang.getText(), kategoriList.get(jComboBox1.getSelectedIndex()), keteranganBarang.getText());
        loadBarang();
    }//GEN-LAST:event_editPemasok3ActionPerformed

    private void hapusPemasok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPemasok3ActionPerformed
        barang.delete(kodeBarang.getText());
        loadBarang();
    }//GEN-LAST:event_hapusPemasok3ActionPerformed

    private void barangTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barangTableMousePressed
        String kode_part = (String) barangTable.getValueAt(barangTable.getSelectedRow(), 1);                            
        String nama_part = (String) barangTable.getValueAt(barangTable.getSelectedRow(), 2);                      
        String kategori_part = (String) barangTable.getValueAt(barangTable.getSelectedRow(), 3);                            
        String keterangan_part = (String) barangTable.getValueAt(barangTable.getSelectedRow(), 5);
        kodeBarang.setText(kode_part);
        namaBarang.setText(nama_part);
        keteranganBarang.setText(keterangan_part);
        for (int i=0; i<jComboBox1.getItemCount(); i++) {
            if (jComboBox1.getModel().getElementAt(i).contains(kategori_part)) {
                jComboBox1.setSelectedIndex(i);
            }
        }
    }//GEN-LAST:event_barangTableMousePressed

    private void gudangTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangTableMousePressed
        String kode_part = (String) gudangTable.getValueAt(gudangTable.getSelectedRow(), 1);                            
        String nama_part = (String) gudangTable.getValueAt(gudangTable.getSelectedRow(), 2);                      
        String alamat_part = (String) gudangTable.getValueAt(gudangTable.getSelectedRow(), 3);                            
        String keterangan_part = (String) gudangTable.getValueAt(gudangTable.getSelectedRow(), 4);
        kodeGudang.setText(kode_part);
        namaGudang.setText(nama_part);
        alamatGudang.setText(alamat_part);
        keteranganGudang.setText(keterangan_part);
    }//GEN-LAST:event_gudangTableMousePressed

    private void kategoriTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategoriTableMousePressed
        String kode_part = (String) kategoriTable.getValueAt(kategoriTable.getSelectedRow(), 1);                            
        String nama_part = (String) kategoriTable.getValueAt(kategoriTable.getSelectedRow(), 2);                             
        String keterangan_part = (String) kategoriTable.getValueAt(kategoriTable.getSelectedRow(), 3);
        kodeKategori.setText(kode_part);
        namaKategori.setText(nama_part);
        keteranganKategori.setText(keterangan_part);
    }//GEN-LAST:event_kategoriTableMousePressed

    private void pemasokTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pemasokTableMousePressed
        String kode_part = (String) pemasokTable.getValueAt(pemasokTable.getSelectedRow(), 1);                            
        String nama_part = (String) pemasokTable.getValueAt(pemasokTable.getSelectedRow(), 2);                             
        String phone_part = (String) pemasokTable.getValueAt(pemasokTable.getSelectedRow(), 3);                       
        String keterangan_part = (String) pemasokTable.getValueAt(pemasokTable.getSelectedRow(), 4);
        kodePemasok.setText(kode_part);
        namaPemasok.setText(nama_part);
        phonePemasok.setText(phone_part);
        keteranganPemasok.setText(keterangan_part);
    }//GEN-LAST:event_pemasokTableMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatGudang;
    private javax.swing.JTable barangTable;
    private javax.swing.JButton editPemasok;
    private javax.swing.JButton editPemasok1;
    private javax.swing.JButton editPemasok2;
    private javax.swing.JButton editPemasok3;
    private javax.swing.JTable gudangTable;
    private javax.swing.JButton hapusPemasok;
    private javax.swing.JButton hapusPemasok1;
    private javax.swing.JButton hapusPemasok2;
    private javax.swing.JButton hapusPemasok3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable kategoriTable;
    private javax.swing.JTextField keteranganBarang;
    private javax.swing.JTextField keteranganGudang;
    private javax.swing.JTextField keteranganKategori;
    private javax.swing.JTextField keteranganPemasok;
    private javax.swing.JTextField kodeBarang;
    private javax.swing.JTextField kodeGudang;
    private javax.swing.JTextField kodeKategori;
    private javax.swing.JTextField kodePemasok;
    private javax.swing.JTextField namaBarang;
    private javax.swing.JTextField namaGudang;
    private javax.swing.JTextField namaKategori;
    private javax.swing.JTextField namaPemasok;
    private javax.swing.JTable pemasokTable;
    private javax.swing.JTable pemasokTable1;
    private javax.swing.JTextField phonePemasok;
    private javax.swing.JButton simpanPemasok;
    private javax.swing.JButton simpanPemasok1;
    private javax.swing.JButton simpanPemasok2;
    private javax.swing.JButton simpanPemasok3;
    private javax.swing.JButton simpanPemasok4;
    // End of variables declaration//GEN-END:variables

    private void loadBarang() {
        Object[] header = {"#", "Kode", "Nama", "Kategori", "Jumlah", "Keterangan"};
        DefaultTableModel model = new DefaultTableModel(null, header);
        barangTable.setModel(model);
        
        ResultSet data = barang.fetchAll();
        int i = 0;
        try {
            while (data.next()){
                String kode_part = data.getString("kode_part");
                String nama_part = data.getString("nama_part");
                String kategori_part = data.getString("kategori");
                int jumlah = data.getInt("jumlah");
                String keterangan = data.getString("keterangan");
                Object[] datum = {++i, kode_part, nama_part, kategori_part, jumlah, keterangan};
                model.addRow(datum);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadKategoriInBarang() {
        String[] body = { };
        DefaultComboBoxModel model = new DefaultComboBoxModel<>( body );
        jComboBox1.setModel( model );
        
        ResultSet data = kategori.fetchAll();
        try {
            kategoriList.clear();
            while (data.next()){
                String kode_kategori = data.getString("kode_kategori");
                String nama_kategori = data.getString("nama_kategori");
                String formatted = "["+ kode_kategori +"] "+ nama_kategori;
                kategoriList.add(nama_kategori);
                model.addElement( formatted );
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadKategori() {
        Object[] header = { "#", "Kode", "Nama", "Keterangan"};
        DefaultTableModel model = new DefaultTableModel( null, header );
        kategoriTable.setModel( model );
        
        ResultSet data = kategori.fetchAll();
        int i = 0;
        try {
            while (data.next()){
                String kode_part = data.getString("kode_kategori");
                String nama_part = data.getString("nama_kategori");
                String keterangan_part = data.getString("keterangan");
                Object[] datum = { ++i, kode_part,nama_part, keterangan_part};
                model.addRow(datum);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadGudang() {
        Object[] header = { "#", "Kode", "Nama", "Alamat", "Keterangan" };
        DefaultTableModel model = new DefaultTableModel( null, header );
        gudangTable.setModel( model );
        
        ResultSet data = gudang.fetchAll();
        int i = 0;
        try {
            while (data.next()){
                String kode_part = data.getString("kode_gudang");
                String nama_part = data.getString("nama_gudang");
                String alamat_part = data.getString("alamat");
                String keterangan_part = data.getString("keterangan");
                Object[] datum = { ++i, kode_part, nama_part, alamat_part, keterangan_part };
                model.addRow(datum);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadPemasok() {
        Object[] header = { "#", "Kode", "Nama", "No. Telepon", "Alamat" };
        DefaultTableModel model = new DefaultTableModel( null, header );
        pemasokTable.setModel( model );
        
        ResultSet data = pemasok.fetchAll();
        int i = 0;
        try {
            while (data.next()){
                String kode_part = data.getString("kode_supplier");
                String nama_part = data.getString("nama_supplier");
                String phone_part = data.getString("notelpon_supplier");
                String alamat_part = data.getString("alamat_supplier");
                Object[] datum = { ++i, kode_part,nama_part, phone_part, alamat_part};
                model.addRow(datum);
            }
        } catch (SQLException ex) {
            Logger.getLogger(DataMasterPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
